---
  - name: Sync data from one NetBox instance to another
    hosts: localhost
    connection: local 
    gather_facts: no
    vars:
      src_netbox_url: '{{ input_src_netbox_url }}'
      src_netbox_token: '{{ input_src_netbox_token }}'
      dst_netbox_url: '{{ input_dst_netbox_url }}'
      dst_netbox_token: '{{ input_dst_netbox_token }}'

    collections:
      - netbox.netbox

    tasks:
      - name: Sync tags
        netbox.netbox.netbox_tag:
          netbox_url: '{{ dst_netbox_url }}'
          netbox_token: '{{ dst_netbox_token }}'
          data:
            name: '{{ item.value.name }}'
            color: '{{ item.value.color }}'
            description: '{{ item.value.description }}'
        loop: "{{ query('netbox.netbox.nb_lookup', 
                  'tags', 
                  api_endpoint=src_netbox_url, 
                  token=src_netbox_token) }}"
        tags:
          - tags

      - name: Sync tenant groups
        netbox.netbox.netbox_tenant_group:
          netbox_url: '{{ dst_netbox_url }}'
          netbox_token: '{{ dst_netbox_token }}'
          data:
            name: '{{ item.value.name }}'
            parent_tenant_group: '{{ item.value.parent|default(omit) }}'
            description: '{{ item.value.description }}'
            tags: '{{ item.value.tags }}'
        loop: "{{ query('netbox.netbox.nb_lookup', 
                  'tenant-groups', 
                  api_endpoint=src_netbox_url, 
                  token=src_netbox_token) }}"
        tags:
          - tenant_groups
